<?xml version="1.0" encoding="UTF-8"?>
<testng-results retried="3" ignored="0" total="5" passed="1" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2024-09-20T20:30:51 IST" name="BST" finished-at="2024-09-20T20:33:52 IST" duration-ms="181480">
    <groups>
      <group name="SmokeTest">
        <method signature="CreateContactTest.createContact()[pri:0, instance:com.crm.vtiger.CreateContact.CreateContactTest@459e9125]" name="createContact" class="com.crm.vtiger.CreateContact.CreateContactTest"/>
      </group> <!-- SmokeTest -->
      <group name="RegressionTest">
        <method signature="CreateContactTest.createContactClone()[pri:0, instance:com.crm.vtiger.CreateContact.CreateContactTest@459e9125]" name="createContactClone" class="com.crm.vtiger.CreateContact.CreateContactTest"/>
      </group> <!-- RegressionTest -->
    </groups>
    <test started-at="2024-09-20T20:30:51 IST" name="Test" finished-at="2024-09-20T20:33:52 IST" duration-ms="181480">
      <class name="com.crm.vtiger.CreateContact.CreateContactTest">
        <test-method is-config="true" signature="lunchBrowser()[pri:0, instance:com.crm.vtiger.CreateContact.CreateContactTest@459e9125]" started-at="2024-09-20T20:30:51 IST" name="lunchBrowser" finished-at="2024-09-20T20:30:54 IST" duration-ms="3110" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- lunchBrowser -->
        <test-method is-config="true" signature="loginToApp()[pri:0, instance:com.crm.vtiger.CreateContact.CreateContactTest@459e9125]" started-at="2024-09-20T20:30:54 IST" name="loginToApp" finished-at="2024-09-20T20:31:00 IST" duration-ms="5588" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginToApp -->
        <test-method retried="true" signature="createContact()[pri:0, instance:com.crm.vtiger.CreateContact.CreateContactTest@459e9125]" started-at="2024-09-20T20:31:00 IST" name="createContact" finished-at="2024-09-20T20:31:24 IST" duration-ms="24672" status="SKIP">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
expected [Administrator - Contacts - vtiger CRM 5 - Commercial Open Source CRM] but found [Administrator - Home - vtiger CRM 5 - Commercial Open Source CRM]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [Administrator - Contacts - vtiger CRM 5 - Commercial Open Source CRM] but found [Administrator - Home - vtiger CRM 5 - Commercial Open Source CRM]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:46)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:30)
at com.crm.vtiger.CreateContact.CreateContactTest.createContact(CreateContactTest.java:79)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:829)
at org.testng.TestRunner.run(TestRunner.java:602)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:431)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:391)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- createContact -->
        <test-method is-config="true" signature="signout()[pri:0, instance:com.crm.vtiger.CreateContact.CreateContactTest@459e9125]" started-at="2024-09-20T20:31:24 IST" name="signout" finished-at="2024-09-20T20:31:31 IST" duration-ms="6414" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- signout -->
        <test-method is-config="true" signature="loginToApp()[pri:0, instance:com.crm.vtiger.CreateContact.CreateContactTest@459e9125]" started-at="2024-09-20T20:31:31 IST" name="loginToApp" finished-at="2024-09-20T20:31:36 IST" duration-ms="5361" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginToApp -->
        <test-method retried="true" signature="createContact()[pri:0, instance:com.crm.vtiger.CreateContact.CreateContactTest@459e9125]" started-at="2024-09-20T20:31:36 IST" name="createContact" finished-at="2024-09-20T20:31:59 IST" duration-ms="23216" status="SKIP">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
expected [Administrator - Contacts - vtiger CRM 5 - Commercial Open Source CRM] but found [Administrator - Home - vtiger CRM 5 - Commercial Open Source CRM]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [Administrator - Contacts - vtiger CRM 5 - Commercial Open Source CRM] but found [Administrator - Home - vtiger CRM 5 - Commercial Open Source CRM]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:46)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:30)
at com.crm.vtiger.CreateContact.CreateContactTest.createContact(CreateContactTest.java:79)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:263)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:62)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:829)
at org.testng.TestRunner.run(TestRunner.java:602)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:431)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:391)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- createContact -->
        <test-method is-config="true" signature="signout()[pri:0, instance:com.crm.vtiger.CreateContact.CreateContactTest@459e9125]" started-at="2024-09-20T20:31:59 IST" name="signout" finished-at="2024-09-20T20:32:06 IST" duration-ms="6513" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- signout -->
        <test-method is-config="true" signature="loginToApp()[pri:0, instance:com.crm.vtiger.CreateContact.CreateContactTest@459e9125]" started-at="2024-09-20T20:32:06 IST" name="loginToApp" finished-at="2024-09-20T20:32:11 IST" duration-ms="5157" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginToApp -->
        <test-method retried="true" signature="createContact()[pri:0, instance:com.crm.vtiger.CreateContact.CreateContactTest@459e9125]" started-at="2024-09-20T20:32:11 IST" name="createContact" finished-at="2024-09-20T20:32:34 IST" duration-ms="22882" status="SKIP">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
expected [Administrator - Contacts - vtiger CRM 5 - Commercial Open Source CRM] but found [Administrator - Home - vtiger CRM 5 - Commercial Open Source CRM]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [Administrator - Contacts - vtiger CRM 5 - Commercial Open Source CRM] but found [Administrator - Home - vtiger CRM 5 - Commercial Open Source CRM]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:46)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:30)
at com.crm.vtiger.CreateContact.CreateContactTest.createContact(CreateContactTest.java:79)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:263)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:62)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:829)
at org.testng.TestRunner.run(TestRunner.java:602)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:431)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:391)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- createContact -->
        <test-method is-config="true" signature="signout()[pri:0, instance:com.crm.vtiger.CreateContact.CreateContactTest@459e9125]" started-at="2024-09-20T20:32:34 IST" name="signout" finished-at="2024-09-20T20:32:41 IST" duration-ms="6889" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- signout -->
        <test-method is-config="true" signature="loginToApp()[pri:0, instance:com.crm.vtiger.CreateContact.CreateContactTest@459e9125]" started-at="2024-09-20T20:32:41 IST" name="loginToApp" finished-at="2024-09-20T20:32:46 IST" duration-ms="5144" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginToApp -->
        <test-method signature="createContact()[pri:0, instance:com.crm.vtiger.CreateContact.CreateContactTest@459e9125]" started-at="2024-09-20T20:32:46 IST" name="createContact" finished-at="2024-09-20T20:33:08 IST" duration-ms="22537" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
expected [Administrator - Contacts - vtiger CRM 5 - Commercial Open Source CRM] but found [Administrator - Home - vtiger CRM 5 - Commercial Open Source CRM]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [Administrator - Contacts - vtiger CRM 5 - Commercial Open Source CRM] but found [Administrator - Home - vtiger CRM 5 - Commercial Open Source CRM]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:46)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:30)
at com.crm.vtiger.CreateContact.CreateContactTest.createContact(CreateContactTest.java:79)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:263)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:62)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:829)
at org.testng.TestRunner.run(TestRunner.java:602)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:431)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:391)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- createContact -->
        <test-method is-config="true" signature="signout()[pri:0, instance:com.crm.vtiger.CreateContact.CreateContactTest@459e9125]" started-at="2024-09-20T20:33:13 IST" name="signout" finished-at="2024-09-20T20:33:15 IST" duration-ms="2425" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- signout -->
        <test-method is-config="true" signature="loginToApp()[pri:0, instance:com.crm.vtiger.CreateContact.CreateContactTest@459e9125]" started-at="2024-09-20T20:33:15 IST" name="loginToApp" finished-at="2024-09-20T20:33:21 IST" duration-ms="5440" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginToApp -->
        <test-method signature="createContactClone()[pri:0, instance:com.crm.vtiger.CreateContact.CreateContactTest@459e9125]" started-at="2024-09-20T20:33:21 IST" name="createContactClone" finished-at="2024-09-20T20:33:45 IST" duration-ms="24319" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- createContactClone -->
        <test-method is-config="true" signature="signout()[pri:0, instance:com.crm.vtiger.CreateContact.CreateContactTest@459e9125]" started-at="2024-09-20T20:33:45 IST" name="signout" finished-at="2024-09-20T20:33:52 IST" duration-ms="6981" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- signout -->
        <test-method is-config="true" signature="closeBrowser()[pri:0, instance:com.crm.vtiger.CreateContact.CreateContactTest@459e9125]" started-at="2024-09-20T20:33:52 IST" name="closeBrowser" finished-at="2024-09-20T20:33:52 IST" duration-ms="521" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeBrowser -->
      </class> <!-- com.crm.vtiger.CreateContact.CreateContactTest -->
    </test> <!-- Test -->
  </suite> <!-- BST -->
</testng-results>
